### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by williamfiset** [AlgoWiki/AlgoWiki#13]
Hi, 

I've noticed a lot of broken links in this repo which is a shame. If you want to get rid of all the broken links for good I recommend you try out the [awesome_bot](https://github.com/dkhamsing/awesome_bot) tool in combination with [Travis Continuous Integration](https://travis-ci.org/). This way after each commit the tool can send you an email if there are any broken links in the repo!

I'm pretty sure I don't have the permissions to add this repo to https://travis-ci.org/ but if you choose to do so add the following .travis.yml file to the repo to trigger broken link checks. I haven't tested it all the way through, but it should probably work? If it's working you should receive an email notifying you.

``` yml
# Install ruby to get gem command
before_install:
  - sudo apt-add-repository -y ppa:brightbox/ruby-ng
  - sudo apt-get -y update
  - sudo apt-get -y install ruby2.4
  - sudo apt-get -y install bash

# Install awesome_bot tool for broken link checking
before_script:
  - gem install awesome_bot

# Run broken link check
script:
  - awesome_bot --files *.md --allow-dupe --allow-redirect
```

Also, don't forget to add a CI build [shield](https://shields.io/)!
